# src files
MAIN_OBJS = \
			EK_TM4C123GXL.o \
			main.o \

HEADERS = \
		  EK_TM4C123GXL.h \

# Adjust paths based on you TivaWare installation location
TIVAWARE_PATH = \mnt\c\ti\TivaWare_C_Series-2.2.0.295
COMPILER = arm-none-eabi-gcc
